### ISSUE TITLE
suggest to add article_id in addition to article_doi

### ISSUE THREAD

**Issue by jhpoelen** [pensoft/pensoft-interaction-tables#11]
In current version of bi_table.json contains links to published table and the doi of the related article. 

```json
{ 
  "table_id" : "<http://openbiodiv.net/FB706B4E-BAC2-4432-AD28-48063E7753E4>",
  "article_doi": "10.3897/zookeys.306.5455"
}
```

to facilitate easy integration with openbiodiv, suggest to include article_id .

For example:

```json
{ 
  "table_id" : "http://openbiodiv.net/FB706B4E-BAC2-4432-AD28-48063E7753E4",
  "article_doi": "10.3897/zookeys.306.5455",
  "article_id" : "http://openbiodiv.net/D37E8D1A-221B-FFA6-FFE7-4458FFA0FFC2"
}
```

This would avoid an intermediate query to retrieve the graph associated with the published article.

(note the removed brackets)

**Comment by mdmtrv** [comment]
Done. Please see https://github.com/pensoft/pensoft-interaction-tables/commit/b9954129d9e368c0885daf76c7817a6d28e6f6fa
