### ISSUE TITLE
taxon names in table captions are not annotated

### ISSUE THREAD

**Issue by jhpoelen** [pensoft/pensoft-interaction-tables#2]
Hi @mdmtrv ! 

I finally got around to taking a stab at a first integration with the annotated pensoft tables.

I noticed that taxon names in tables are annotated, however, names in table captions are not.

Example caption of table 2 of https://doi.org/10.3897/zookeys.297.4695 does have annotated name (see screenshot) - 
![Screenshot from 2020-07-11 14-37-30](https://user-images.githubusercontent.com/1084872/87234323-9f10d000-c384-11ea-90a0-1deee59a671c.png)

However, the captions included in bi_tables do not have the annotated taxon names (e.g., with the taxon-name tags).

```
$ cat bi_tables_20200630.json | grep "10.3897/zookeys.297.4695" | jq .caption
"Host plants of Jadera haematoloma at different localities and reports of aggregation behaviour or mass occurrence based on literature data.<br/>"
"Collected individuals of Jadera haematoloma in the investigated sites of Kaohsiung City and Tainan City (for description of the sites see text).<br/>"
"Body size (in mm) and relative length of the labium in specimens of different sex collected from different host plants (all macropterous).<br/>"
```

Please let me know if there's some other way to get this content.

**Comment by mdmtrv** [comment]
I've [added a new json file](https://github.com/pensoft/pensoft-interaction-tables/commit/bb7d1dc9f2eba220a61502e06e6114053fd30788) which has a caption_xml field, containing the caption xml (for tables with caption). The caption xmls should include an annotation of taxonomic names via the taxon-name tags.

**Comment by jhpoelen** [comment]
@mdmtrv thanks for adding the new json with caption_xml field. Hoping to integrate this shortly (see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/526)
