### ISSUE TITLE
review taxon hierarchy lookup sparql 

### ISSUE THREAD

**Issue by jhpoelen** [pensoft/pensoft-interaction-tables#6]
hi @mdmtrv - As you suggested, please suggest improvement to the sparql query for taxon hierarchy lookup in openbiodiv: 

https://github.com/globalbioticinteractions/globalbioticinteractions/blob/92ff38f0eaee7bb5427b7f7b4b7e64dc3e4d3787/eol-globi-data-sources/src/main/java/org/eol/globi/data/StudyImporterForPensoft.java#L241

**Comment by mdmtrv** [comment]
@jhpoelen Please see https://github.com/mdmtrv/globalbioticinteractions/blob/main/eol-globi-data-sources/src/main/java/org/eol/globi/data/StudyImporterForPensoft.java (Perhaps there was an easier way to share the modified file)
I edited both sparql queries. The taxon hierarchy lookup one does not need a limit if you specify the rdf:type of the ?id.
I updated the other one with the list of authors and the publication year. 
Hopefully it works, let me know if it doesn't.

**Comment by jhpoelen** [comment]
Closing stale issue.
