### ISSUE TITLE
nanopub format for species interactions

### ISSUE THREAD

**Issue by jhpoelen** [pensoft/pensoft-interaction-tables#8]
@mdmtrv as promised, here's an example of a (trusty) nanopub created using ```elton nanopubs```

see also 
[nanopub.trig.txt](https://github.com/pensoft/pensoft-interaction-tables/files/4914393/nanopub.trig.txt)

```
@prefix this: <http://purl.org/np/RALDYlbmt5ysWXnNjWwK1Z_iH_PF-f7QYB_SRi_X6JFVc> . @prefix sub: <http://purl.org/np/RALDYlbmt5ysWXnNjWwK1Z_iH_PF-f7QYB_SRi_X6JFVc#> . @prefix np: <http://www.nanopub.org/nschema#> . @prefix dcterms: <http://purl.org/dc/terms/> . @prefix prov: <http://www.w3.org/ns/prov#> . @prefix pav: <http://swan.mindinformatics.org/ontologies/1.2/pav/> . @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . @prefix obo: <http://purl.obolibrary.org/obo/> .  sub:Head { 	this: np:hasAssertion sub:Assertion ; 		np:hasProvenance sub:Provenance ; 		np:hasPublicationInfo sub:Pubinfo ; 		a np:Nanopublication . }  sub:Assertion { 	sub:Interaction obo:RO_0000057 sub:Organism_1 , sub:Organism_2 ; 		a obo:GO_0044419 . 	 	sub:Organism_1 obo:RO_0002437 sub:Organism_2 ; 		a <http://openbiodiv.net/61980887-4C69-40FB-9F43-208E06EAB1A8> ; 		rdfs:label "Amaryllidaceae" . 	 	sub:Organism_2 a <http://openbiodiv.net/22A7F215-829B-458A-AEBB-39FFEA6D4A91> ; 		rdfs:label "Bolacothrips striatopennatus" . }  sub:Provenance { 	sub:Assertion prov:wasDerivedFrom <https://doi.org/10.3897/zookeys.306.5455> . 	 	<https://doi.org/10.3897/zookeys.306.5455> dcterms:bibliographicCitation "Identification of the terebrantian thrips (Insecta, Thysanoptera) associated with cultivated plants&#160;in&#160;Java, Indonesia. http://openbiodiv.net/D37E8D1A-221B-FFA6-FFE7-4458FFA0FFC2. 10.3897/zookeys.306.5455" . }  sub:Pubinfo { 	<file:///media/jorrit/data/globi/data/pensoft-interaction-tables/./> dcterms:bibliographicCitation "Mariya Dimitrova. 2020. Annotated biotic interaction tables from Pensoft publications." . 	 	this: dcterms:license <https://creativecommons.org/licenses/by/4.0/> ; 		pav:createdBy <https://doi.org/10.5281/zenodo.998263> ; 		prov:wasDerivedFrom <file:///media/jorrit/data/globi/data/pensoft-interaction-tables/./> . } 
```

**Comment by mdmtrv** [comment]
We don't have a strict proposed format yet but I think this one fits with what we envision. I especially like the Assertion format:
`sub:Assertion { 	
sub:Interaction obo:RO_0000057 sub:Organism_1 , sub:Organism_2 ;
 		a obo:GO_0044419 . 	 	
sub:Organism_1 obo:RO_0002437 sub:Organism_2 ; 	...`
I was thinking of a more simple `sub:Organism_1  obo:RO_0002437 sub:Organism_2` but defining `sub:Interaction obo:RO_0000057 sub:Organism_1 , sub:Organism_2 ;` is more informative and can be extended with a more specific interaction if such is extracted later.

**Comment by mdmtrv** [comment]
I noticed now that the openbiodiv identifier for the article is also included inside the bibliographicCitation. I think the doi is sufficient and the openbiodiv id is unnecessary. Also, in the pubInfo you have "Mariya Dimitrova. 2020. Annotated biotic interaction tables from Pensoft publications."  as the bibliographicCitation of the nanopublication itself. Maybe having 'OpenBiodiv' as the source is more suitable since it was automatically extracted, rather than manually. (Even though here both OpenBiodiv and GloBI should be mentioned as technically GloBI indexed it as a nanopublication). This is a complicated matter.

**Comment by jhpoelen** [comment]
> We don't have a strict proposed format yet but I think this one fits with what we envision. I especially like the Assertion format:
> `sub:Assertion { sub:Interaction obo:RO_0000057 sub:Organism_1 , sub:Organism_2 ; a obo:GO_0044419 . sub:Organism_1 obo:RO_0002437 sub:Organism_2 ; ...`
> I was thinking of a more simple `sub:Organism_1 obo:RO_0002437 sub:Organism_2` but defining `sub:Interaction obo:RO_0000057 sub:Organism_1 , sub:Organism_2 ;` is more informative and can be extended with a more specific interaction if such is extracted later.

Thanks for sharing your suggestion. I agree that the ```sub:Organism_1 obo:RO_0002437 sub:Organism_2``` is a little simpler, sort of like a shortcut. Perhaps we can simply add the assertion to the existing ones as another way to interpret the same reported interaction?

**Comment by jhpoelen** [comment]
> I noticed now that the openbiodiv identifier for the article is also included inside the bibliographicCitation. I think the doi is sufficient and the openbiodiv id is unnecessary. Also, in the pubInfo you have "Mariya Dimitrova. 2020. Annotated biotic interaction tables from Pensoft publications." as the bibliographicCitation of the nanopublication itself. Maybe having 'OpenBiodiv' as the source is more suitable since it was automatically extracted, rather than manually. (Even though here both OpenBiodiv and GloBI should be mentioned as technically GloBI indexed it as a nanopublication). This is a complicated matter.

You can change the dataset citation in ```globi.json```. As far as the OpenBiodiv ID usage in the reference - is there a way to reference the specific table with a DOI?

**Comment by mdmtrv** [comment]
> > I noticed now that the openbiodiv identifier for the article is also included inside the bibliographicCitation. I think the doi is sufficient and the openbiodiv id is unnecessary. Also, in the pubInfo you have "Mariya Dimitrova. 2020. Annotated biotic interaction tables from Pensoft publications." as the bibliographicCitation of the nanopublication itself. Maybe having 'OpenBiodiv' as the source is more suitable since it was automatically extracted, rather than manually. (Even though here both OpenBiodiv and GloBI should be mentioned as technically GloBI indexed it as a nanopublication). This is a complicated matter.
> 
> You can change the dataset citation in `globi.json`. As far as the OpenBiodiv ID usage in the reference - is there a way to reference the specific table with a DOI?

Ah yes, I remember you changed the globi.json in our previous meeting. Regarding tables, they do not have a DOI or any other identifier for now.

**Comment by jhpoelen** [comment]
Note that nanopubs can now be generated via Elton using:

```
# locally clone pensoft tables and related resources
elton update pensoft/pensoft-interaction-tables
# generate nanopubs
elton nanopubs
```

@tkuhn - some tables from articles published by Pensoft Publishers can now be used to generated nanopubs! Hoping to catch up some time soon to revisit GloBI contributions (and now, indirectly Pensoft) to the nanopub universe.
