### ISSUE TITLE
openbiodiv.org down?

### ISSUE THREAD

**Issue by jhpoelen** [pensoft/pensoft-interaction-tables#9]
As I was running some unit tests just now, I noticed that http code 503 Service Unavailable are generated when accessing http://graph.openbiodiv.net/ .  Please let me know if there's something I should do to access the sparql endpoint again.

![Screenshot from 2020-07-14 14-38-39](https://user-images.githubusercontent.com/1084872/87479249-fb236080-c5df-11ea-9a2c-a1d0624a3464.png)

**Comment by mdmtrv** [comment]
It's now up and running again.

**Comment by jhpoelen** [comment]
@mdmtrv thanks! Curious to hear the root cause if you are willing/able to share.
